# ubuntu 18 probably. 
FROM ubuntu:latest

RUN apt-get update
RUN apt-get -y install openjdk-8-jdk-headless git
RUN apt-get -y install maven
RUN mkdir -p /home/librarycloud/ingest/cameldata 
RUN cd  /home/librarycloud/ && git clone https://github.com/harvard-library/librarycloud_ingest.git
RUN cd /home/librarycloud/librarycloud_ingest && git checkout dockerized_ingest
#ADD persistence.xml /home/librarycloud/librarycloud_ingest/src/main/resources/META-INF/persistence.xml
#RUN mkdir -p /home/librarycloud/librarycloud_ingest
#RUN cd /home/librarycloud/librarycloud_ingest
WORKDIR /home/librarycloud/librarycloud_ingest
RUN mvn clean install -Dmaven.test.skip=true
CMD mvn camel:run -q -Dmaven.test.skip=true > /dev/null
